### ISSUE TITLE
error in treesub java.io.IOException: Cannot run program "/usr/bin/unbuffer" (in directory "/home/..."): error=2, No such file or directory

### ISSUE THREAD

**Issue by JuaninAR** [tamuri/treesub#9]
How do I solve the error: 

java.io.IOException: Cannot run program "/usr/bin/unbuffer" (in directory "/home/DARWINION/jacosta/Documents/prueba-ts"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at treesub.gui.AnnotatorGUI$RunAction$RunWorker.doInBackground(Unknown Source)
	at treesub.gui.AnnotatorGUI$RunAction$RunWorker.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

**Comment by JuaninAR** [comment]
attached a screen with the error from treesub
![Screenshot from 2019-06-11 16-08-47](https://user-images.githubusercontent.com/51721102/59301474-10ed8600-8c68-11e9-86c6-16250a5c9e75.png)
![Screenshot from 2019-06-11 16-08-47](https://user-images.githubusercontent.com/51721102/59301500-1fd43880-8c68-11e9-896c-bb5f91fc7c4a.png)

**Comment by JuaninAR** [comment]
I solve this problem, we have installed the expect dpkg package and treesub run!!!
![Screenshot from 2019-06-21 15-33-56](https://user-images.githubusercontent.com/51721102/59944061-3b92c800-943a-11e9-9c7b-0afa87151d2a.png)

**Comment by virologist** [comment]
Hi, JuaninAR

I meet the exact same problem with you. Could you pl give me some clues for what kinds of expect dpkg package(s) should install?
![ScreenShot00037](https://user-images.githubusercontent.com/54756814/82744369-f42f5d00-9da9-11ea-8e98-5e431fd019ef.jpg)

#####  update ### 
Ok, I figure it out. 
install the package named “expect”
_sudo apt-get install -y expect_

**Another question for Tamuri**
Should we modify the default Raxml parameters in streesub in order to build a more robust tree to interpret the amnio acid substitutions?
the default parameters
_RAXML_OPTIONS=-m GTRGAMMA -T 2 -\# 10 -p 12345_
modify to 
_RAXML_OPTIONS=-f a -m GTRGAMMAI -p 12345 -N 10000 -T 16_

Thanks for JuaninAR && Tamuri
